import jsPDF from "jspdf";

interface Header { header_name?: string; name?: string; present: boolean; value: string | null }
interface Scan {
  website: string;
  https_status: boolean;
  ssl_valid: boolean;
  ssl_expires_at: string | null;
  ssl_issuer: string | null;
  security_score: number;
  response_time_ms: number;
  scan_date: string;
}

export function generateReportPdf(scan: Scan, headers: Header[]) {
  const doc = new jsPDF();
  const marginX = 15;
  let y = 20;

  doc.setFontSize(22);
  doc.setTextColor(20, 130, 100);
  doc.text("Website Security Report", marginX, y);
  y += 6;
  doc.setDrawColor(20, 130, 100);
  doc.line(marginX, y, 195, y);
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  const rows: [string, string][] = [
    ["Website", scan.website],
    ["Scan Date", new Date(scan.scan_date).toLocaleString()],
    ["HTTPS", scan.https_status ? "Secure" : "Not Secure"],
    ["SSL Certificate", scan.ssl_valid ? "Valid" : "Not Valid"],
    ["SSL Issuer", scan.ssl_issuer ?? "—"],
    ["SSL Expires", scan.ssl_expires_at ? new Date(scan.ssl_expires_at).toLocaleDateString() : "—"],
    ["Response Time", `${scan.response_time_ms} ms`],
    ["Security Score", `${scan.security_score} / 100`],
  ];
  for (const [k, v] of rows) {
    doc.setFont("helvetica", "bold");
    doc.text(k + ":", marginX, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(v), marginX + 45, y);
    y += 7;
  }

  y += 6;
  doc.setFontSize(14);
  doc.setTextColor(20, 130, 100);
  doc.text("Security Headers", marginX, y);
  y += 8;
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  headers.forEach((h) => {
    const label = h.header_name ?? h.name ?? "";
    doc.setFont("helvetica", "bold");
    doc.text(label, marginX, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(h.present ? 25 : 190, h.present ? 130 : 60, h.present ? 60 : 60);
    doc.text(h.present ? "Present" : "Missing", marginX + 90, y);
    doc.setTextColor(50, 50, 50);
    y += 6;
    if (y > 275) { doc.addPage(); y = 20; }
  });

  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text("Generated by SecureAudit", marginX, 290);

  const safeHost = scan.website.replace(/[^a-z0-9.-]/gi, "_");
  doc.save(`security-report-${safeHost}-${Date.now()}.pdf`);
}
